### ISSUE TITLE
Render only pages where code changed.

### ISSUE THREAD

**Issue by pouledodue** [esteinberg/plantuml4idea#120]
The issue: 
Complex diagrams containing many pages are slow to render, because it seems all pages are rendered each time.
as a result: slow performance.

Possible improvement:
Render only pages where code changed.
(if nothing changed between two 'newpage' tag, don't re-render it, use previously rendered image.

**Comment by krasa** [comment]
pages are already rendered only when changed, unless you switch to other image and then back,

**Comment by krasa** [comment]
So I implemented it, and also some caching of images in general. The code is quite complex now, hopefully I did not broke it too much...

**Comment by pouledodue** [comment]
Could you tell me how I can build a .jar with theses sources?

**Comment by krasa** [comment]
- create project, import .iml file (I just pushed it)
- setup SDK - http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html - select installed IntelliJ for which you then select JDK.
- Build | Prepore Plugin module...

**Comment by pouledodue** [comment]
ok trying that thanks

**Comment by pouledodue** [comment]
compiled OK however when in Pycharm I get 
 NoClassDefFoundError: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils

**Comment by krasa** [comment]
Looks like a missing library. 
Did it generate a zip file? 
And you installed that zip file? 
And '.PyCharmXX\config\plugins\plantuml4idea\lib' contains plantuml4idea.jar and plantuml*.jar ?

**Comment by pouledodue** [comment]
oops working now 
I was loading the .jar not the entire .zip

**Comment by pouledodue** [comment]
ok tested that. there is 2 bugs:
- Images are not rendered automatically. I have to click "Render PlantUML Diagram" to render an image.
- When I select a specific page in the "Select Page" Dropdown, I get "NullPointerException: null" in the Event Log. The image is not generated. If I click "Render PlantUML Diagram", the image appears.

**Comment by krasa** [comment]
stacktrace?

**Comment by pouledodue** [comment]
Pycharm 5.0.2 143.1184

null
java.lang.NullPointerException
	at org.plantuml.idea.toolwindow.PlantUmlLabel.setup(PlantUmlLabel.java:38)
	at org.plantuml.idea.toolwindow.PlantUmlLabel.<init>(PlantUmlLabel.java:28)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayImage(PlantUmlToolWindow.java:235)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayDiagram(PlantUmlToolWindow.java:227)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$4$1.run(PlantUmlToolWindow.java:201)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
I was unable to reproduce it, but made some improvements, try it now please.

**Comment by pouledodue** [comment]
ok testing it in 5 minutes

**Comment by krasa** [comment]
BTW if included file contains  a newpage, then all pages will be always rendered. Maybe I will fix it...

**Comment by pouledodue** [comment]
The 2 bugs are corrected. Works well now.

However, there is only a small adjustment left to fix:
If I two .puml documents open...
Say the first document has 17 pages and the second document has only 3 pages.
If I select the 16th page and then switch to the second document, I get a `java.lang.ArrayIndexOutOfBoundsException: 2` (possibly because the page 16 does not exist on the second document???)

2
java.lang.ArrayIndexOutOfBoundsException: 2
	at org.plantuml.idea.rendering.RenderCacheItem.imageMissing(RenderCacheItem.java:82)
	at org.plantuml.idea.rendering.RenderCacheItem.renderRequired(RenderCacheItem.java:47)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$3.run(PlantUmlToolWindow.java:194)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
So that condition I deleted was needed after all... :)
Fixed.

**Comment by pouledodue** [comment]
There is one bug left.
As soon there is a syntax error in my file, it seems to try to reprocess all my pages. So it takes like 1 minute to render each time I make a syntax error.

And  I got this at the same time:

trying to display null image. selectedPage=-1, nullPage=0, cacheItem=org.plantuml.idea.rendering.RenderCacheItem@640e6765[version=499,sourceFilePath=/Users/danielcyr/cyr/cyr/b/docs/uml/use.puml,baseDir=/Users/danielcyr/cyr/cyr/b/docs/uml,zoom=100,page=4,includedFiles={},imageResult=org.plantuml.idea.rendering.RenderResult@371ea391[diagrams=[org.plantuml.idea.rendering.RenderResult$Diagram@51616848[page=4,description=(0 entities) (31 entities) (38 entities) (25 entities) (32 entities) (26 entities) (0 entities) (15 entities) (15 entities) (13 entities) (16 entities) (7 entities) (5 entities) (21 entities) (32 entities) (23 entities) (30 entities),diagramBytesLength=71471]],pages=17,renderRequest=org.plantuml.idea.rendering.RenderRequest@436841fb[baseDir=/Users/danielcyr/cyr/cyr/b/docs/uml,format=PNG,page=4,zoom=100,version=499]],imagesWithData=[null, null, null, org.plantuml.idea.util.ImageWithUrlData@54ca23bc[hasImage=true], org.plantuml.idea.util.ImageWithUrlData@168a009f[hasImage=true], null, org.plantuml.idea.util.ImageWithUrlData@4c73092e[hasImage=true], org.plantuml.idea.util.ImageWithUrlData@4d95eec2[hasImage=true], null, null, null, null, null, null, null, null, null]]
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayImage(PlantUmlToolWindow.java:274)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayDiagram(PlantUmlToolWindow.java:263)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand.postRenderOnEDT(PlantUmlToolWindow.java:242)
	at org.plantuml.idea.rendering.RenderCommand$1.run(RenderCommand.java:58)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pouledodue** [comment]
1 bug left:
As I soon as I have a Syntax Error in my file (example, while typing...), I get the "syntax error?" image, and then the problem: it seems to reprocess the complete document (so it takes like 1 minute).

Ans I got this error when it happens:

trying to display null image. selectedPage=-1, nullPage=0, cacheItem=org.plantuml.idea.rendering.RenderCacheItem@640e6765[version=499,sourceFilePath=/,baseDir=/,zoom=100,page=4,includedFiles={},imageResult=org.plantuml.idea.rendering.RenderResult@371ea391[diagrams=[org.plantuml.idea.rendering.RenderResult$Diagram@51616848[page=4,description=(0 entities) (31 entities) (38 entities) (25 entities) (32 entities) (26 entities) (0 entities) (15 entities) (15 entities) (13 entities) (16 entities) (7 entities) (5 entities) (21 entities) (32 entities) (23 entities) (30 entities),diagramBytesLength=71471]],pages=17,renderRequest=org.plantuml.idea.rendering.RenderRequest@436841fb[baseDir=/,format=PNG,page=4,zoom=100,version=499]],imagesWithData=[null, null, null, org.plantuml.idea.util.ImageWithUrlData@54ca23bc[hasImage=true], org.plantuml.idea.util.ImageWithUrlData@168a009f[hasImage=true], null, org.plantuml.idea.util.ImageWithUrlData@4c73092e[hasImage=true], org.plantuml.idea.util.ImageWithUrlData@4d95eec2[hasImage=true], null, null, null, null, null, null, null, null, null]]
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayImage(PlantUmlToolWindow.java:274)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayDiagram(PlantUmlToolWindow.java:263)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand.postRenderOnEDT(PlantUmlToolWindow.java:242)
	at org.plantuml.idea.rendering.RenderCommand$1.run(RenderCommand.java:58)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
Reproduced and fixed.

But, wow, 1 minute? 
Do you use links? 
```
@startuml
url of Class01 is [[http://google.com]]
abstract class AbstractList
@enduml
```
because SVG takes a lot of time, I could add a settings for disabling it...

**Comment by pouledodue** [comment]
no links.
I still have the problem with your latest version:

(I type an incomplete syntax) --> (40 seconds of 100% CPU  Usage) --> (the image "..skipping 400 lines...blabla Syntax Error?" appears)

**Comment by krasa** [comment]
please enable debug logs by adding '#org.plantuml' to [Help | Debug Log Settings] and send me the log.

**Comment by krasa** [comment]
I disabled links, try it.

**Comment by pouledodue** [comment]
here is the log
[idea.txt](https://github.com/esteinberg/plantuml4idea/files/276377/idea.txt)

**Comment by krasa** [comment]
Looks correct, it rendered error - which itself is crazy slow, that is a problem of plantuml itself, and then you probably fixed it back so it had nothing to render and displayed all from cache.

**Comment by krasa** [comment]
Btw what CPU do you have? Some 2 core? 
I would recommend disabling editor syntax checking in settings.

**Comment by pouledodue** [comment]
yes MBP core duo 2.26Ghz 2009

**Comment by pouledodue** [comment]
yup tested plantuml in Terminal : 21 seconds to tell me there is a parse error. ugh

**Comment by krasa** [comment]
You seriously need to upgrade...

Why do you even have such big document? Wouldn't it be better to split it or use some visual tool instead?

I don't see anything more to optimize now, unless I would start to save image to disk, so I can keep bigger cache... I bet your image must be killing the heap.

**Comment by pouledodue** [comment]
it's just 17 small pages in one document.

**Comment by pouledodue** [comment]
your plugin send each page separately to plantuml right?

**Comment by krasa** [comment]
no, it takes the whole document, and I request rendering of specific pages by their index.

**Comment by pouledodue** [comment]
ok that's consistent with the 22 seconds behavior. 
Originally I thought that only the one modified 'newpage' section was sent each time, based on a checksum of that content. That would fix the 22 seconds problem

**Comment by krasa** [comment]
That could be done, but e.g. sequence diagram would look totally different. Which diagram you use?

**Comment by pouledodue** [comment]
Currently I use 
-use cases
-class
-component

but I will use sequence too for sure.

I don't know for now how they will be affected, I did not test yet how they behave with 'newpage'..

**Comment by pouledodue** [comment]
maybe the plugin could have a parameter to choose either the current "send whole+request index" rendering strategy or a new one thats sends each page's code separately to plantuml.

**Comment by krasa** [comment]
Yep, you will be able to make a comment on the start e.g.
`idea.partialRender
`idea.disableSyntaxCheck

I saw an improvement from 30s to 3s by splitting it!

**Comment by krasa** [comment]
Implemented, you can enable it by putting on the first page
`idea.partialRender`
`idea.disableSyntaxCheck`
as a comment with `'` or whatever 

I have not seen such dramatic improvements with other diagram types, apart from when syntax is broken - I will report a bug on plantuml ...

For example http://pastebin.com/qA1TwsUA
- 4,5s to render normally -> 20s to syntax error image without error
- 6s rendering splitted by pages ->  instant error rendering

**Comment by pouledodue** [comment]
lightning faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaast !

**Comment by pouledodue** [comment]
There is a small issue with `scale`.
Here is how it is currently handled in:
1. plantuml
2. your plugin (old version)
3. your plugin (new lightning version)

1. plantuml:
using `scale 0.2` scales the page to 0.2

2. your plugin (old version)
In order to `scale 0.2` to work properly, on must add the `newpage` tag at top of a document

3. your plugin (new lightning version)
`scale 0.2` does not work at all.

**Comment by krasa** [comment]
Is it reported on plantuml tracker?

**Comment by pouledodue** [comment]
isn't the bug in the plugin? `scale` is ok if I render the page in command line with plantuml 8041

**Comment by krasa** [comment]
Hmm, I see, the problem is my plugin overrides the scale, when there is only one page.

**Comment by krasa** [comment]
fixed

**Comment by pouledodue** [comment]
Do you think it could remember the page it is on when switching between two .puml documents

**Comment by krasa** [comment]
sure, do you want it to be remembered between restarts?

**Comment by pouledodue** [comment]
would be a nice addition

**Comment by krasa** [comment]
So plantuml made a fix, and 30s error render reduced to 100ms :-)

**Comment by pouledodue** [comment]
great!

**Comment by krasa** [comment]
please try the new version
https://github.com/esteinberg/plantuml4idea/releases/tag/2.0.0-SNAPSHOT

**Comment by pouledodue** [comment]
seems to work great!
